name: portfolio build
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.21.3
      
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/about-me/
            sudo git pull origin main
            docker image build -t portfolio
            docker run -it -p 80:80 portfolio --rm -name portfolio
            
            
